(()=>{"use strict";
const SAVE_KEY="yousyas-game-web-save-v1",VERSION=1,SECRET="YG-WEB::the-voice-beyond-the-board::2026",D=[[-1,0],[0,1],[1,0],[0,-1]],SWORD=["|","—","|","—"];
const $=s=>document.querySelector(s),ui={stage:$("#ascii-stage"),scene:$("#scene-name"),turn:$("#turn-counter"),speaker:$("#speaker"),text:$("#dialogue"),choices:$("#choice-list"),hp:$("#stat-hp"),money:$("#stat-money"),kills:$("#stat-kills"),chapter:$("#stat-stage"),objective:$("#objective-title"),detail:$("#objective-detail"),bar:$("#objective-bar"),save:$("#save-modal"),help:$("#help-modal"),code:$("#save-code"),saveStatus:$("#save-status")};
const fresh=()=>({version:VERSION,mode:"menu",scene:"menu",stage:0,turn:0,paused:false,player:{x:0,y:0,dir:1,hp:3,maxHp:3,money:0,beacon:null},map:[],enemies:[],kills:0,stageKills:0,collected:0,relics:0,flags:{barrier:false,beacon:false},endings:[],speaker:"SYSTEM",message:"等待勇者回应。"});
let state=fresh(),locked=false;
const scripts={
prologue:[["SYSTEM","连接已建立。请保持清醒。","继续"],["你","……这是哪儿？","环顾四周"],["那个声音","你醒了，勇者。","“勇者？”"],["那个声音","你被召唤到了艾瑞斯世界。红色魔王卡洛梅正在吞噬四大古陆，而你将终结这一切。","听下去"],["那个声音","先学会活下来。蓝色 O 是你，身前的线条是剑。WASD 移动，方向键转动武器。","开始训练"]],
afterCoins:[["那个声音","很好。金币既是资源，也是你施展能力的代价。","继续"],["那个声音","接下来是战斗。你的行动先于魔物；让剑碰到它们的身体或武器。","面对木偶"]],
afterTraining:[["那个声音","比我预想得更快。现在，木偶会开始移动和寻找你。","继续"],["那个声音","按 C 在身后放置障碍，花费 3 金币；按 F 设置或返回信标，每次花费 5 金币。","接受试炼"]],
beforeEmber:[["那个声音","教程结束。现在你已具备踏入真正战场的资格。","继续"],["那个声音","第一站是赤烬之地。找到三枚炎核碎片，并抵达东北方祭坛。","前往赤烬之地"]],
emberFinish:[["那个声音","炎核在你手中搏动，如同一颗仍有温度的心脏。","继续"],["你","这里的魔物……为什么会留下人类的徽记？","追问"],["那个声音","战场会制造许多相似的遗物。不要让无关的问题动摇你。","沉默"],["SYSTEM","WEB EDITION · CHAPTER I CLEAR。后续大陆尚未在原版中完成，本次存档会保留你的通关记录。","返回标题"]]};
function choices(items){ui.choices.replaceChildren();items.forEach(x=>{const b=document.createElement("button");b.className="story-choice";b.textContent=x.label;b.onclick=x.action;ui.choices.append(b)})}
function say(w,t){state.speaker=w;state.message=t;ui.speaker.textContent=w;ui.text.textContent=t}
function script(name,done,i=0){stopAll();state.mode="story";locked=true;render();const l=scripts[name][i];say(l[0],l[1]);choices([{label:l[2],action:()=>i+1<scripts[name].length?script(name,done,i+1):(locked=false,done())}])}
function menu(){state.mode="menu";state.scene="menu";state.paused=false;$("#pause-button").textContent="暂停";ui.stage.innerHTML='<div class="title-art"><strong>ＹＯＵＳＹＡ’Ｓ</strong><span>Ｇ　Ａ　Ｍ　Ｅ</span></div>';ui.scene.textContent="YOUSYA // AWAITING SIGNAL";say("SYSTEM","选择一个存档入口。关键进度会自动保存在这个浏览器中。");const a=[{label:"新游戏",action:newGame}];if(localStorage.getItem(SAVE_KEY))a.push({label:"继续游戏",action:loadLocal});a.push({label:"存档导入 / 导出",action:()=>ui.save.showModal()});choices(a);hud()}
function newGame(){state=fresh();script("prologue",coinStage)}
function map(w,h){return Array.from({length:h},(_,x)=>Array.from({length:w},(_,y)=>x===0||y===0||x===h-1||y===w-1?"#":" "))}
function walls(a,rs){rs.forEach(([x1,y1,x2,y2])=>{for(let x=x1;x<=x2;x++)for(let y=y1;y<=y2;y++)a[x][y]="#"})}
function reset(x,y,m=state.player.money){state.player={x,y,dir:1,hp:3,maxHp:3,money:m,beacon:null}}
function foe(x,y,dir,moving=true){return{x,y,dir,moving,alive:true,sight:moving?8:0}}
function begin(scene,stage,w,h,x,y,m){state.scene=scene;state.stage=stage;state.mode="play";state.paused=false;$("#pause-button").textContent="暂停";state.map=map(w,h);reset(x,y,m);state.stageKills=0;state.enemies=[];choices([])}
function coinStage(){begin("coins",1,25,17,8,3,0);walls(state.map,[[4,5,4,9],[10,14,13,14],[7,18,11,18]]);[[3,19],[8,11],[13,5]].forEach(p=>state.map[p[0]][p[1]]="$");state.collected=0;say("那个声音","收集地图上的 3 枚金币。WASD 移动；方向键改变剑的方向。");saveLocal();render()}
function training(){begin("training",2,27,17,8,4,Math.max(30,state.player.money));walls(state.map,[[4,6,4,10],[11,16,11,20],[7,13,9,13]]);state.enemies=[foe(3,19,3,false),foe(7,20,3,false),foe(13,7,1,false),foe(13,22,3,false)];say("那个声音","击破 4 个训练木偶。转动武器本身也可以攻击。");saveLocal();render()}
function skill(){begin("skill",3,31,19,9,3,Math.max(50,state.player.money));walls(state.map,[[4,8,4,15],[9,20,14,20],[13,5,13,11],[7,25,10,25]]);[[3,26],[15,25],[15,3],[6,17]].forEach(p=>state.map[p[0]][p[1]]="$");state.enemies=[foe(3,24,2),foe(7,17,3),foe(14,26,0),foe(15,8,1),foe(4,18,2)];state.flags.barrier=state.flags.beacon=true;say("那个声音","击破 5 个会移动的木偶。敌人的正前方 120° 为视野。");saveLocal();render()}
function ember(){begin("ember",4,43,25,22,3,Math.max(45,state.player.money));walls(state.map,[[3,8,3,17],[3,26,3,34],[7,4,13,4],[7,14,7,24],[6,34,13,34],[12,9,12,18],[16,5,16,14],[16,24,16,37],[20,11,20,27],[8,28,12,28]]);[[5,11],[14,31],[21,7]].forEach(p=>state.map[p[0]][p[1]]="◆");[[5,37],[10,20],[14,7],[18,39],[21,31],[9,6]].forEach(p=>state.map[p[0]][p[1]]="$");state.map[2][39]="X";state.enemies=[foe(5,20,2),foe(5,38,3),foe(9,31,2),foe(10,8,1),foe(14,20,3),foe(18,17,0),foe(19,35,3),foe(22,28,0)];state.relics=0;say("那个声音","寻找 3 枚炎核碎片 ◆，然后前往东北方祭坛 X。");saveLocal();render()}
const sword=u=>({x:u.x+D[u.dir][0],y:u.y+D[u.dir][1]}),wall=(x,y)=>!state.map[x]||["#","*"].includes(state.map[x][y]);
function collect(x,y){const t=state.map[x]?.[y];if(t==="$"){state.player.money+=10;state.collected++;state.map[x][y]=" ";say("SYSTEM","获得 10 枚金币。")}else if(t==="◆"){state.relics++;state.map[x][y]=" ";say("SYSTEM",`炎核碎片产生了回应（${state.relics}/3）。`);saveLocal()}}
function input(key){if(state.mode!=="play"||locked||state.paused)return;key=key.length===1?key.toLowerCase():key;let acted=false,mi={w:0,d:1,s:2,a:3}[key],ti={ArrowUp:0,ArrowRight:1,ArrowDown:2,ArrowLeft:3}[key];if(mi!==undefined){let x=state.player.x+D[mi][0],y=state.player.y+D[mi][1],sp={x:x+D[state.player.dir][0],y:y+D[state.player.dir][1]};if(!wall(x,y)&&!wall(sp.x,sp.y)){state.player.x=x;state.player.y=y;collect(x,y);acted=true}else say("SYSTEM","前方无法通过。")}else if(ti!==undefined){state.player.dir=ti;acted=true}else if(key==="c"&&state.flags.barrier)acted=barrier();else if(key==="f"&&state.flags.beacon)acted=beacon();else if(key==="e")acted=interact();if(!acted)return render();playerAttack();objectives();render()}
function barrier(){if(state.player.money<3)return say("SYSTEM","金币不足，需要 3 枚。"),false;let d=(state.player.dir+2)%4,x=state.player.x+D[d][0],y=state.player.y+D[d][1];if(state.map[x]?.[y]!==" ")return say("SYSTEM","这里无法放置障碍。"),false;state.player.money-=3;state.map[x][y]="*";say("SYSTEM","人造障碍已部署。");return true}
function beacon(){if(state.player.money<5)return say("SYSTEM","金币不足，需要 5 枚。"),false;state.player.money-=5;if(state.player.beacon){Object.assign(state.player,state.player.beacon);state.player.beacon=null;say("SYSTEM","已返回信标并回收。")}else{state.player.beacon={x:state.player.x,y:state.player.y};say("SYSTEM","信标已设置。")}return true}
function interact(){if(state.scene==="ember"&&state.map[state.player.x]?.[state.player.y]==="X"){if(state.relics<3)return say("那个声音",`还缺少 ${3-state.relics} 枚炎核碎片。`),false;state.stage=5;if(!state.endings.includes("chapter-one"))state.endings.push("chapter-one");saveLocal();script("emberFinish",menu);return true}say("SYSTEM","这里没有可调查的事物。");return false}
function playerAttack(){let ps=sword(state.player);state.enemies.forEach(e=>{let es=sword(e);if((ps.x===e.x&&ps.y===e.y)||(ps.x===es.x&&ps.y===es.y)){e.alive=false;state.kills++;state.stageKills++;say("SYSTEM","目标已击破。")}});state.enemies=state.enemies.filter(e=>e.alive)}
function sees(e){let vx=state.player.x-e.x,vy=state.player.y-e.y,dist=Math.hypot(vx,vy);if(dist>e.sight)return false;let dot=vx*D[e.dir][0]+vy*D[e.dir][1];return dot>0&&dot*dot*4>=vx*vx+vy*vy}
function free(e,x,y,d){let sp={x:x+D[d][0],y:y+D[d][1]};return!wall(x,y)&&!wall(sp.x,sp.y)&&!state.enemies.some(o=>o!==e&&o.alive&&(o.x===x&&o.y===y))}
function enemiesMove(){state.enemies.forEach(e=>{if(!e.moving)return;let dirs;if(sees(e)){let v=state.player.x>e.x?2:0,h=state.player.y>e.y?1:3;dirs=Math.abs(state.player.x-e.x)>=Math.abs(state.player.y-e.y)?[v,h]:[h,v]}else{let q=(state.turn+e.x*3+e.y)%4;dirs=[q,(q+1)%4,(q+3)%4]}for(let d of dirs){let x=e.x+D[d][0],y=e.y+D[d][1];if(free(e,x,y,d)){e.x=x;e.y=y;e.dir=d;break}}})}
function enemyAttack(){let p=state.player,ps=sword(p);for(let e of state.enemies){let es=sword(e),hit=(e.x===p.x&&e.y===p.y)||(es.x===p.x&&es.y===p.y)||(state.scene==="skill"&&es.x===ps.x&&es.y===ps.y);if(hit){e.alive=false;p.hp--;say("SYSTEM",`受到攻击。剩余生命 ${p.hp}/${p.maxHp}。`);break}}state.enemies=state.enemies.filter(e=>e.alive);if(p.hp<=0)gameOver()}
function spawnDummy(moving){let spots=[[2,2],[2,state.map[0].length-3],[state.map.length-3,2],[state.map.length-3,state.map[0].length-3],[3,Math.floor(state.map[0].length/2)],[state.map.length-4,Math.floor(state.map[0].length/2)]];for(let i=0;i<spots.length;i++){let[x,y]=spots[(i+state.turn)%spots.length],dir=(state.turn+i)%4;if(Math.abs(x-state.player.x)+Math.abs(y-state.player.y)<7||wall(x,y)||state.enemies.some(e=>Math.abs(e.x-x)+Math.abs(e.y-y)<3))continue;let e=foe(x,y,dir,moving);if(free(e,x,y,dir)){state.enemies.push(e);return true}}return false}
function replenishDummies(){if(state.scene==="training"){let wanted=Math.min(2,4-state.stageKills);while(state.enemies.length<wanted&&spawnDummy(false));}else if(state.scene==="skill"){let wanted=Math.min(3,5-state.stageKills);while(state.enemies.length<wanted&&spawnDummy(true));}}
function worldTick(){if(state.mode!=="play"||locked||state.paused||document.hidden||ui.save.open||ui.help.open)return;state.turn++;replenishDummies();if(state.turn%2===0){enemiesMove();enemyAttack();replenishDummies();objectives();render()}}
function togglePause(force){if(state.mode!=="play")return;state.paused=typeof force==="boolean"?force:!state.paused;stopAll();$("#pause-button").textContent=state.paused?"继续":"暂停";$("#pause-button").classList.toggle("primary",!state.paused);if(state.paused)say("SYSTEM","游戏已暂停。按 Space / P 或点击“继续”恢复。");else say("SYSTEM","游戏继续。");render()}
function objectives(){if(state.scene==="coins"&&state.collected>=3)script("afterCoins",training);else if(state.scene==="training"&&state.stageKills>=4)script("afterTraining",skill);else if(state.scene==="skill"&&state.stageKills>=5)script("beforeEmber",ember);else if(state.scene==="ember"&&state.relics>=3&&state.player.x===2&&state.player.y===39)say("SYSTEM","祭坛就在脚下。按 E 调查。")}
function gameOver(){state.mode="end";let end=state.scene==="training"?"找错人了":state.scene==="skill"?"技不如人":"出师未捷身先死";if(!state.endings.includes(end))state.endings.push(end);say("那个声音",`你倒在棋盘上。达成结局：${end}。`);choices([{label:"从本章重新开始",action:()=>({coins:coinStage,training,skill,ember}[state.scene]||ember)()},{label:"返回标题",action:menu}]);saveLocal();render()}
function objective(){if(state.scene==="coins")return["基础移动",`收集金币 ${state.collected}/3`,state.collected/3];if(state.scene==="training")return["战斗训练",`击破木偶 ${state.stageKills}/4`,state.stageKills/4];if(state.scene==="skill")return["技能试炼",`击破移动木偶 ${state.stageKills}/5`,state.stageKills/5];if(state.scene==="ember")return["赤烬之地",`炎核碎片 ${state.relics}/3；集齐后前往东北祭坛`,state.relics/3];return["开始游戏","选择新游戏，或读取本地存档。",0]}
function hud(){ui.hp.textContent=state.stage?`${Math.max(0,state.player.hp)} / ${state.player.maxHp}`:"—";ui.money.textContent=state.stage?state.player.money:"—";ui.kills.textContent=state.stage?state.kills:"—";ui.chapter.textContent=["序章","教程 I","教程 II","教程 III","第一章","完成"][state.stage]||"序章";let[o,d,p]=objective();ui.objective.textContent=o;ui.detail.textContent=d;ui.bar.style.width=`${Math.min(100,p*100)}%`;ui.turn.textContent=`TURN ${String(state.turn).padStart(4,"0")}`}
function sightCells(e){let out=[];if(!e.moving)return out;for(let x=e.x-e.sight;x<=e.x+e.sight;x++)for(let y=e.y-e.sight;y<=e.y+e.sight;y++){let vx=x-e.x,vy=y-e.y,dot=vx*D[e.dir][0]+vy*D[e.dir][1];if(dot>0&&vx*vx+vy*vy<=e.sight*e.sight&&dot*dot*4>=vx*vx+vy*vy)out.push([x,y])}return out}
function renderMap(){let vh=Math.min(19,state.map.length),vw=Math.min(31,state.map[0].length),sx=Math.max(0,Math.min(state.player.x-Math.floor(vh/2),state.map.length-vh)),sy=Math.max(0,Math.min(state.player.y-Math.floor(vw/2),state.map[0].length-vw)),c=Array.from({length:vh},(_,x)=>Array.from({length:vw},(_,y)=>({ch:state.map[x+sx][y+sy],cl:tile(state.map[x+sx][y+sy])})));const put=(x,y,ch,cl)=>{if(c[x]?.[y])c[x][y]={ch,cl}};state.enemies.forEach(e=>sightCells(e).forEach(([x,y])=>{if(state.map[x]?.[y]===" ")put(x-sx,y-sy,"·","tile-sight")}));if(state.player.beacon)put(state.player.beacon.x-sx,state.player.beacon.y-sy,"P","tile-beacon");state.enemies.forEach(e=>{let s=sword(e);put(s.x-sx,s.y-sy,SWORD[e.dir],"tile-enemy");put(e.x-sx,e.y-sy,"O","tile-enemy")});let ps=sword(state.player);put(ps.x-sx,ps.y-sy,SWORD[state.player.dir],"tile-player");put(state.player.x-sx,state.player.y-sy,"O","tile-player");let pre=document.createElement("pre");pre.className="ascii-map";c.forEach((r,i)=>{r.forEach(q=>{let s=document.createElement("span");s.className=q.cl;s.textContent=q.ch;pre.append(s)});if(i+1<c.length)pre.append("\n")});ui.stage.replaceChildren(pre)}
function tile(t){return t==="#"?"tile-wall":t==="$"?"tile-coin":t==="◆"?"tile-relic":t==="X"?"tile-altar":""}
function render(){if(state.mode!=="menu"&&state.map.length){renderMap();ui.scene.textContent={coins:"TRAINING // MOVEMENT",training:"TRAINING // COMBAT",skill:"TRAINING // FIELD SKILLS",ember:"CONTINENT I // EMBERLAND"}[state.scene]||"YOUSYA // STORY"}ui.speaker.textContent=state.speaker;ui.text.textContent=state.message;hud()}
const b64=b=>{let s="";b.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")},unb=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((s.length+3)%4)),c=>c.charCodeAt(0));
async function key(salt){let m=await crypto.subtle.importKey("raw",new TextEncoder().encode(SECRET),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:120000,hash:"SHA-256"},m,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function encrypt(data){let salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(salt),cipher=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},k,new TextEncoder().encode(JSON.stringify(data)))),p=new Uint8Array(29+cipher.length);p[0]=VERSION;p.set(salt,1);p.set(iv,17);p.set(cipher,29);return"YG1."+b64(p)}
async function decrypt(code){if(!code.startsWith("YG1."))throw Error("存档版本或格式不正确");let p=unb(code.slice(4).trim());if(p.length<46||p[0]!==VERSION)throw Error("存档数据不完整");try{let plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:p.slice(17,29)},await key(p.slice(1,17)),p.slice(29)),data=JSON.parse(new TextDecoder().decode(plain));if(!data.player||!Array.isArray(data.endings))throw 0;return data}catch{throw Error("存档校验失败：内容可能已损坏或被修改")}}
async function saveLocal(){try{localStorage.setItem(SAVE_KEY,await encrypt(state))}catch{}}
async function loadLocal(){try{state=await decrypt(localStorage.getItem(SAVE_KEY));state.paused=false;$("#pause-button").textContent="暂停";state.mode=state.map?.length?"play":"menu";locked=false;choices([]);say("SYSTEM","本地存档已读取。");render()}catch(e){say("SYSTEM",e.message);render()}}
$("#pause-button").onclick=()=>togglePause();$("#save-button").onclick=()=>{stopAll();ui.saveStatus.textContent="";ui.save.showModal()};$("#help-button").onclick=()=>{stopAll();ui.help.showModal()};$("#export-save").onclick=async()=>{let c=await encrypt(state);ui.code.value=c;try{await navigator.clipboard.writeText(c);ui.saveStatus.textContent="存档码已生成并复制。"}catch{ui.saveStatus.textContent="存档码已生成，请手动复制。"}};$("#import-save").onclick=async()=>{try{state=await decrypt(ui.code.value.trim());state.paused=false;await saveLocal();state.mode=state.map?.length?"play":"menu";choices([]);say("SYSTEM","存档导入成功。");ui.save.close();render()}catch(e){ui.saveStatus.textContent=e.message}};$("#clear-save").onclick=()=>{localStorage.removeItem(SAVE_KEY);ui.code.value="";ui.saveStatus.textContent="本地存档已清除。"};
const repeatable=new Set(["w","a","s","d","ArrowUp","ArrowRight","ArrowDown","ArrowLeft"]),held=new Map();
function normalizeKey(k){return k.length===1?k.toLowerCase():k}
function startHold(k){k=normalizeKey(k);if(held.has(k))return;input(k);if(repeatable.has(k)){let timer=setInterval(()=>input(k),95);held.set(k,timer)}else held.set(k,0)}
function stopHold(k){k=normalizeKey(k);let timer=held.get(k);if(timer)clearInterval(timer);held.delete(k)}
function stopAll(){held.forEach(timer=>{if(timer)clearInterval(timer)});held.clear()}
document.addEventListener("keydown",e=>{let k=normalizeKey(e.key);if((k===" "||k==="p")&&!ui.save.open&&!ui.help.open){e.preventDefault();if(!e.repeat)togglePause();return}let a=["w","a","s","d","c","f","e","ArrowUp","ArrowRight","ArrowDown","ArrowLeft"];if(!a.includes(k)||ui.save.open||ui.help.open)return;e.preventDefault();if(!e.repeat)startHold(k)});
document.addEventListener("keyup",e=>stopHold(e.key));window.addEventListener("blur",stopAll);document.addEventListener("visibilitychange",()=>{if(document.hidden)stopAll()});
document.querySelectorAll("[data-key]").forEach(b=>{const down=e=>{e.preventDefault();startHold(b.dataset.key)},up=e=>{e.preventDefault();stopHold(b.dataset.key)};b.addEventListener("pointerdown",down);b.addEventListener("pointerup",up);b.addEventListener("pointercancel",up);b.addEventListener("pointerleave",up)});
setInterval(worldTick,320);
menu();
})();
